### ISSUE TITLE
Add libxlsxwriter topic to the GitHub project metadata

### ISSUE THREAD

**Issue by jmcnamara** [aalvarado/libxlsxwriter_ruby#1]
Hi,

Could you add libxlsxwriter as a "topic" metadata to your project so that users can find wrappers in different languages.

Topic/Metadata are shown at the top of the project: https://github.com/jmcnamara/libxlsxwriter

Other examples: https://github.com/search?q=topic%3Alibxlsxwriter&type=Repositories

I'll probably add a section on language wrappings to the libxlsxwriter documentation.

Thanks,

John

**Comment by aalvarado** [comment]
Hi @jmcnamara unfortunately I've have abandoned this project in favor of someone who was able to successfully create a wrapper for your library. https://github.com/Paxa/fast_excel .

I should probably add that this is not a working gem to the README. Apologies for the inconvenience.

**Comment by jmcnamara** [comment]
No problem. Thanks for letting me know.
